'use client'

import React from 'react'
import { Download, FileText, Image as ImageIcon } from 'lucide-react'

interface ExportButtonProps {
  data: any
  playerName: string
}

export default function ExportButton({ data, playerName }: ExportButtonProps) {
  const [isOpen, setIsOpen] = React.useState(false)

  const exportAsJSON = () => {
    const jsonString = JSON.stringify(data, null, 2)
    const blob = new Blob([jsonString], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${playerName.replace(/\s+/g, '-')}-analysis-${new Date().toISOString().split('T')[0]}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setIsOpen(false)
  }

  const exportAsCSV = () => {
    const { stats, propType } = data
    const metricMap: Record<string, string> = {
      points: 'points',
      rebounds: 'rebounds',
      assists: 'assists'
    }
    const targetMetric = metricMap[propType] || 'points'

    // CSV Headers
    const headers = ['Date', 'Opponent', 'Home/Away', propType.toUpperCase(), 'Minutes']
    const rows = stats.map((game: any) => [
      game.game_date,
      game.opponent,
      game.is_home ? 'Home' : 'Away',
      game[targetMetric] || 0,
      game.minutes_played || 0
    ])

    const csvContent = [
      headers.join(','),
      ...rows.map((row: any[]) => row.join(','))
    ].join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${playerName.replace(/\s+/g, '-')}-stats-${new Date().toISOString().split('T')[0]}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setIsOpen(false)
  }

  const exportAsMarkdown = () => {
    const { stats, odds, analysis, propType, advancedMetrics, riskScore } = data
    const metricMap: Record<string, string> = {
      points: 'points',
      rebounds: 'rebounds',
      assists: 'assists'
    }
    const targetMetric = metricMap[propType] || 'points'
    const avgValue = stats.length > 0
      ? stats.reduce((sum: number, g: any) => sum + (g[targetMetric] || 0), 0) / stats.length
      : 0

    let markdown = `# ${playerName} - ${propType.toUpperCase()} Analysis\n\n`
    markdown += `**Date:** ${new Date().toLocaleDateString()}\n\n`

    if (odds) {
      markdown += `## 📊 Betting Information\n\n`
      markdown += `- **Best Line:** ${odds.bestLine.line} (${odds.bestLine.sportsbook})\n`
      markdown += `- **Consensus:** ${odds.consensus}\n`
      markdown += `- **Books Offering:** ${odds.allLines.length}\n`
      markdown += `- **Game:** ${odds.game.awayTeam} @ ${odds.game.homeTeam}\n\n`
    }

    markdown += `## 📈 Performance Metrics\n\n`
    markdown += `- **Season Average:** ${avgValue.toFixed(1)} ${propType}\n`

    if (advancedMetrics) {
      markdown += `- **Consistency Score:** ${advancedMetrics.consistency}%\n`
      markdown += `- **Trend:** ${advancedMetrics.trendDirection}\n`
      markdown += `- **Recent Form:** ${advancedMetrics.recentMomentum}\n`
      markdown += `- **Volatility:** ${advancedMetrics.volatility}%\n\n`
    }

    if (riskScore) {
      markdown += `## ⚠️ Risk Assessment\n\n`
      markdown += `- **Risk Level:** ${riskScore.level}\n`
      markdown += `- **Risk Score:** ${riskScore.score}/100\n\n`
      markdown += `**Risk Factors:**\n`
      riskScore.factors.forEach((factor: string) => {
        markdown += `- ${factor}\n`
      })
      markdown += `\n`
    }

    markdown += `## 🤖 AI Analysis\n\n${analysis}\n\n`

    markdown += `## 📋 Recent Games\n\n`
    markdown += `| Date | Opponent | Location | ${propType.toUpperCase()} | Minutes |\n`
    markdown += `|------|----------|----------|---------|----------|\n`
    stats.forEach((game: any) => {
      markdown += `| ${game.game_date} | ${game.opponent} | ${game.is_home ? 'Home' : 'Away'} | ${game[targetMetric] || 0} | ${game.minutes_played || 0} |\n`
    })

    markdown += `\n---\n*Generated by Player Prop Research Tool*\n`

    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${playerName.replace(/\s+/g, '-')}-report-${new Date().toISOString().split('T')[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setIsOpen(false)
  }

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white rounded-lg font-semibold transition-colors"
      >
        <Download className="w-4 h-4" />
        Export
      </button>

      {isOpen && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 z-40"
            onClick={() => setIsOpen(false)}
          />

          {/* Dropdown Menu */}
          <div className="absolute right-0 mt-2 w-56 bg-slate-800 border border-slate-700 rounded-lg shadow-xl z-50">
            <div className="p-2 space-y-1">
              <button
                onClick={exportAsMarkdown}
                className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-slate-200 hover:bg-slate-700 rounded-lg transition-colors"
              >
                <FileText className="w-4 h-4 text-emerald-400" />
                <div>
                  <div className="font-medium">Markdown Report</div>
                  <div className="text-xs text-slate-400">Full analysis (.md)</div>
                </div>
              </button>

              <button
                onClick={exportAsCSV}
                className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-slate-200 hover:bg-slate-700 rounded-lg transition-colors"
              >
                <FileText className="w-4 h-4 text-blue-400" />
                <div>
                  <div className="font-medium">CSV Stats</div>
                  <div className="text-xs text-slate-400">Game log (.csv)</div>
                </div>
              </button>

              <button
                onClick={exportAsJSON}
                className="w-full flex items-center gap-3 px-3 py-2 text-left text-sm text-slate-200 hover:bg-slate-700 rounded-lg transition-colors"
              >
                <FileText className="w-4 h-4 text-purple-400" />
                <div>
                  <div className="font-medium">JSON Data</div>
                  <div className="text-xs text-slate-400">Raw data (.json)</div>
                </div>
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  )
}
